apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: skaffold-introduction
  name: skaffold-introduction
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: skaffold-introduction
  type: LoadBalancer
status:
  loadBalancer: { }
